CC: 100
CO2_price: 85
E_limit: .inf
MIPGap: 0.01
MS: 0.1
VOLL: 6350
data_folder_name: elec_s_37_all
expansion_factor: 3
model_id: 37 all
model_name: GTSEP_v0
p_max_new_branch: 5000
p_min_new_branch: 100
run_id: GTSEP_v0-37 all-Feb15_Sat_h13
save_folder: /cluster/home/tinusfa/master_project/runs/single_runs/GTSEP_v0-37 all-Feb15_Sat_h13
