
marginal_cost: 0          # Cost per kWh (in €/kWh)
investment_cost_permwh: 200000  # Investment cost (in €/MWh)
lifetime: 15      # Battery lifetime in years
discount_rate: 0.07     # Discount rate (7%)
hour_capacity: 2       # Number of hours of storage capacity at rated power
# Power limits (in MW)
P_discharge_min: 0
P_discharge_max: 200000
P_charge_min: 0
P_charge_max: 200000
cdrate: 1.0     # Charge/Discharge rate i.e. P_dicharge_max/P_charge_max = cdrate
# State-of-Charge (SOC) limits in fraction of the total capacity
SOC_min: 0.10
SOC_max: 0.90
daily_leakage: 0.001    # Daily leakage rate (in fraction of the current soc)
efficiency_charge: 0.98        # Charging efficiency
efficiency_discharge: 0.97     # Discharging efficiency


