CC: 100
CO2_price: 85
E_limit: .inf
MIPGap: 0.01
MS: 0.1
VOLL: 0
data_folder_name: elec_s_37_ES_PT
expansion_factor: 2.0
model_id: test small 2
model_name: GTSEP_v0
p_max_new_branch: 3000
p_min_new_branch: 100
run_id: 2_GTSEP_v0-test small 2-Feb13_Thu_h09
save_folder: C:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\runs\batch_runs\2_GTSEP_v0-test
  small 2-Feb13_Thu_h09
