CC: 100
CO2_price: 80
EVPI: false
E_limit: .inf
MIPGap: 0.01
MS: 0.1
VOLL: 6350
VSS: false
battery_capacity_path: null
branch_capacity_path: null
carriers:
- CCGT
- solar
- onwind
clustering_periods: null
clustering_unit: null
co2_emissions_path: /cluster/home/tinusfa/master_project/data/co2_emissions_files/co2_emissions_1_May16_Fri_h23_m07_s45-GTSEP_stochastic_v1-128_ES_PT_emissionsreduction_0.4.csv
data_folder_name: elec_s_128_ES_PT_no_bat_limit
discount_rate: 0.07
expansion_factor: 2.0
generator_capacity_path: null
model_id: 128_ES_PT
model_name: GTSEP_stochastic_v1
p_max_new_branch: 5000
p_min_new_branch: 100
query: not (x > 2 and y < 40)
representative_period_unit: week
representative_periods:
- 11
- 21
- 42
- 52
save_folder: /cluster/home/tinusfa/master_project/runs/batch_runs/batch_128_4_batandnobat_sens_limit/3_May18_Sun_h22_m49_s19-GTSEP_stochastic_v1-128_ES_PT/VSS_runs/EV_run
scenario_file: mean
week_weights:
  11: 13.035714285714286
  21: 13.035714285714286
  42: 13.035714285714286
  52: 13.035714285714286
years:
- 2025
- 2030
- 2040
- 2050
