data_folder_name: elec_s_128_ES_PT
model_name: 
model_id: "No name"
MIPGap: 0.01
# Parameters
VOLL: 6350        # Value of Lost Load [€/MWh]
CC: 100               # Curtailment cost [€/MWh]
CO2_price: 85         # Price of CO2 emissions [€/ton]
E_limit: .inf         # CO2 emissions limit (using YAML's infinity representation)
p_max_new_branch: 5000  # Maximum capacity of new branches [MW]
p_min_new_branch: 100   # Minimum capacity of new branches [MW]
expansion_factor: 0.2   # Expansion factor: existing generator capacity can be expanded by this fraction
MS: 0.1               # Maximum shed at each node