data_folder_name: elec_s_128_ES_PT_no_bat_limit
query: not (x > 2 and y < 40)
model_name: GTSEP_stochastic_v1
model_id: 128_ES_PT
carriers:
- CCGT
- solar
- onwind
years:
- 2025
- 2030
- 2040
- 2050
discount_rate: 0.07
expansion_factor: 0.5
representative_period_unit: week
representative_periods:
- 11
- 21
- 42
- 52
yearly_discount: 500
