CC: 100
CO2_price: 100
EVPI: true
E_limit: .inf
MIPGap: 0.01
MS: 0.1
VOLL: 6350
VSS: true
battery_capacity_path: null
branch_capacity_path: null
carriers:
- CCGT
- solar
- onwind
clustering_periods: null
clustering_unit: null
co2_emissions_path: null
data_folder_name: elec_s_128_ES_PT_no_bat
discount_rate: 0.07
expansion_factor: 2.0
generator_capacity_path: null
model_id: 128_ES_PT_no_bat
model_name: GTSEP_stochastic_v1
p_max_new_branch: 5000
p_min_new_branch: 100
query: not (x > 2 and y < 40)
representative_period_unit: week
representative_periods:
- 11
- 21
- 42
- 52
run_id: 7_May19_Mon_h00_m15_s32-GTSEP_stochastic_v1-128_ES_PT_no_bat
save_folder: /cluster/home/tinusfa/master_project/runs/batch_runs/batch_128_4_batandnobat_sens_co2price/7_May19_Mon_h00_m15_s32-GTSEP_stochastic_v1-128_ES_PT_no_bat
scenario_file: null
week_weights:
  11: 13.035714285714286
  21: 13.035714285714286
  42: 13.035714285714286
  52: 13.035714285714286
years:
- 2025
- 2030
- 2040
- 2050
