data_folder_name: elec_s_37_ES_PT_no_bat_limit
query: "not (x > 2 and y < 40)"
model_name: "GTSEP_v1_multi"
carriers:
- CCGT
- solar
- onwind
years: [2025, 2035, 2045]
discount_rate: 0.07
expansion_factor: 2.0