CC: 100
CO2_price: 85
E_limit: .inf
MIPGap: 0.01
MS: 0.1
VOLL: 6350
carriers:
- CCGT
- solar
- onwind
data_folder_name: elec_s_128_ES_PT_no_bat_limit
expansion_factor: 0.2
model_id: null
model_name: GTSEP_v1
p_max_new_branch: 5000
p_min_new_branch: 100
query: not (x > 2 and y < 40)
run_id: 2_Feb20_Thu_h09-GTSEP_v1
save_folder: /cluster/home/tinusfa/master_project/runs/batch_runs/128-v0-v1-v2/2_Feb20_Thu_h09-GTSEP_v1
